export interface PricingPlan {
  id: string;
  name: string;
  nameAr: string;
  price: number;
  priceAr: string;
  period: string;
  periodAr: string;
  tagline: string;
  taglineAr: string;
  description: string;
  descriptionAr: string;
  competitive?: string;
  competitiveAr?: string;
  savings?: string;
  savingsAr?: string;
  badge?: string;
  badgeAr?: string;
  popular?: boolean;
  features: {
    text: string;
    textAr: string;
    included: boolean;
    highlight?: boolean;
    unique?: boolean;
  }[];
  cta: string;
  ctaAr: string;
  ctaLink: string;
}

export const pricingPlans: PricingPlan[] = [
  {
    id: "free",
    name: "Free Starter",
    nameAr: "البداية المجانية",
    price: 0,
    priceAr: "مجاناً",
    period: "/month + 5% commission",
    periodAr: "/شهرياً + عمولة 5%",
    tagline: "Start Smart, Scale Fast",
    taglineAr: "ابدأ بذكاء، توسّع بسرعة",
    description: "Perfect for testing and small projects",
    descriptionAr: "مثالي للتجربة والمشاريع الصغيرة",
    competitive: "Full features - only pay when you sell",
    competitiveAr: "كل المزايا - ادفع فقط عند البيع",
    features: [
      {
        text: "Launch & sell from day one - no developer needed",
        textAr: "ابدأ البيع من اليوم الأول - بدون مبرمج",
        included: true,
        highlight: true,
      },
      {
        text: "🔥 DreamToApp Store Exposure (Free Traffic!)",
        textAr: "🔥 عرض في متجر DreamToApp (زيارات مجانية!)",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Unlimited Products",
        textAr: "منتجات غير محدودة",
        included: true,
        highlight: true,
      },
      {
        text: "Product Image Gallery",
        textAr: "ألبوم صور للمنتجات",
        included: true,
        highlight: true,
      },
      {
        text: "Product Video Upload",
        textAr: "إضافة فيديو للمنتج",
        included: true,
        highlight: true,
      },
      {
        text: "Media Storage: 1 GB",
        textAr: "مساحة تخزين: 1 جيجا",
        included: true,
      },
      {
        text: "Unlimited Orders",
        textAr: "طلبات غير محدودة",
        included: true,
        highlight: true,
      },
      {
        text: "Store Health Monitoring",
        textAr: "مراقبة صحة المتجر",
        included: true,
        highlight: true,
        unique: true,
      },
      {
        text: "Driver Management System",
        textAr: "نظام إدارة السائقين",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Real-time Driver Tracking",
        textAr: "تتبع السائقين في الوقت الفعلي",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Basic Analytics Dashboard",
        textAr: "لوحة تحليلات أساسية",
        included: true,
      },
      {
        text: "Progressive Web App (PWA)",
        textAr: "تطبيق ويب تقدمي (PWA)",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Discount & Coupon System",
        textAr: "نظام الخصومات والكوبونات",
        included: true,
        highlight: true,
      },
      {
        text: "Product Bundles & Packages",
        textAr: "عروض حزم المنتجات",
        included: true,
        highlight: true,
      },
      {
        text: "AI Product Descriptions (100/month)",
        textAr: "وصف منتجات بالذكاء الاصطناعي (100/شهرياً)",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "SEO Optimized Store",
        textAr: "متجر محسّن لمحركات البحث",
        included: true,
        highlight: true,
      },
      {
        text: "SEO Settings Per Product",
        textAr: "تحسين SEO لكل منتج",
        included: true,
        highlight: true,
      },
      {
        text: "SEO Settings Per Category",
        textAr: "تحسين SEO لكل تصنيف",
        included: true,
        highlight: true,
      },
      {
        text: "Built-in Blog System",
        textAr: "نظام مدونة مدمج",
        included: true,
        highlight: true,
      },
      {
        text: "SEO Settings Per Blog Post",
        textAr: "تحسين SEO لكل مقال",
        included: true,
        highlight: true,
      },
      {
        text: "Auto-share blog posts to Twitter",
        textAr: "مشاركة تلقائية للمقالات على تويتر",
        included: true,
        highlight: true,
      },
      {
        text: "Amazon Integration (Global Marketplace)",
        textAr: "تكامل أمازون (سوق عالمي)",
        included: true,
        highlight: true,
      },
      {
        text: "Trendyol Integration (Fashion & Lifestyle)",
        textAr: "تكامل ترينديول (أزياء ومنتجات)",
        included: true,
        highlight: true,
      },
      {
        text: "Jahez Integration (Food Delivery)",
        textAr: "تكامل جاهز (توصيل طعام)",
        included: true,
        highlight: true,
      },
      {
        text: "Customer Management",
        textAr: "إدارة العملاء",
        included: true,
      },
      {
        text: "Inventory Management & Stock Control",
        textAr: "إدارة المخزون ومراقبة المخزون",
        included: true,
        highlight: true,
      },
      {
        text: "Low Stock SMS Alerts",
        textAr: "تنبيه SMS عند نفاذ المخزون",
        included: true,
        highlight: true,
      },
      {
        text: "ZATCA E-Invoice Compliance (Fatoora)",
        textAr: "إرسال فاتورة ضريبية إلكترونية",
        included: true,
        highlight: true,
      },
      {
        text: "Mini Accounting System",
        textAr: "نظام محاسبة مبسط",
        included: true,
        highlight: true,
      },
      {
        text: "Customer Reviews & Ratings",
        textAr: "تقييمات ومراجعات العملاء",
        included: true,
        highlight: true,
      },
      {
        text: "SEO-Optimized Reviews (Rich Snippets)",
        textAr: "تحسين SEO للتقييمات (نجوم جوجل)",
        included: true,
        highlight: true,
      },
      {
        text: "SMS Order Notifications",
        textAr: "إشعارات SMS للطلبات",
        included: true,
        highlight: true,
      },
      {
        text: "Instagram Shopping Integration",
        textAr: "تكامل التسوق عبر إنستقرام",
        included: true,
        highlight: true,
      },
      {
        text: "Tabby & Tamara BNPL",
        textAr: "تابي وتمارا - اشتر الآن وادفع لاحقاً",
        included: true,
        highlight: true,
      },
      {
        text: "All payments in your name",
        textAr: "كل المدفوعات باسمك مباشرة",
        included: true,
        highlight: true,
      },
      {
        text: "Payment Processing (All Gateways)",
        textAr: "معالجة الدفع (جميع البوابات)",
        included: true,
      },
      {
        text: "Cash on Delivery (COD)",
        textAr: "الدفع عند الاستلام",
        included: true,
        highlight: true,
      },
      {
        text: "Ship locally & internationally - one contract",
        textAr: "شحن محلي ودولي من عقد واحد",
        included: true,
        highlight: true,
      },
      {
        text: "Stable hosting during peak seasons",
        textAr: "استضافة مستقرة في المواسم والذروة",
        included: true,
        highlight: true,
      },
      {
        text: "Shipping Integrations (SMSA, Aramex)",
        textAr: "تكامل الشحن (SMSA، أرامكس)",
        included: true,
      },
      {
        text: "Custom Domain",
        textAr: "نطاق مخصص",
        included: true,
      },
      {
        text: "Email Marketing Automation",
        textAr: "أتمتة التسويق عبر البريد",
        included: true,
        highlight: true,
      },
      {
        text: "Advanced Analytics",
        textAr: "تحليلات متقدمة",
        included: true,
      },
      {
        text: "Shift Management System",
        textAr: "نظام إدارة المناوبات",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Unlimited Team Members",
        textAr: "أعضاء فريق غير محدودين",
        included: true,
        highlight: true,
      },
      {
        text: "Advanced Store Health Reports",
        textAr: "تقارير صحة المتجر المتقدمة",
        included: true,
        highlight: true,
      },
      {
        text: "API Access & Webhooks",
        textAr: "الوصول إلى API والخطافات",
        included: true,
      },
      {
        text: "Custom CSS/JS",
        textAr: "CSS/JS مخصص",
        included: true,
      },
      {
        text: "SMS Marketing",
        textAr: "التسويق عبر الرسائل النصية",
        included: true,
      },
      {
        text: "Priority Email Support",
        textAr: "دعم بريدي ذو أولوية",
        included: true,
      },
      {
        text: "Priority Phone & Chat Support",
        textAr: "دعم هاتفي ودردشة ذو أولوية",
        included: true,
      },
      {
        text: "Dedicated Account Manager",
        textAr: "مدير حساب خاص لك",
        included: true,
        highlight: true,
      },
      {
        text: "Remove DreamToApp Branding",
        textAr: "إزالة علامة DreamToApp",
        included: true,
      },
      {
        text: "24/7 Community Support",
        textAr: "دعم المجتمع على مدار الساعة",
        included: true,
      },
      {
        text: "DreamToApp Branding",
        textAr: "علامة DreamToApp التجارية",
        included: true,
      },
    ],
    cta: "Start Free",
    ctaAr: "ابدأ مجاناً",
    ctaLink: "https://myshop.dreamto.app/auth/register",
  },
  {
    id: "master",
    name: "Master",
    nameAr: "ماستر",
    price: 79,
    priceAr: "٧٩",
    period: "SAR/month + 3% commission",
    periodAr: "ر.س/شهرياً + عمولة 3%",
    tagline: "Everything You Need to Grow",
    taglineAr: "كل ما تحتاجه للنمو",
    description: "For growing businesses ready to scale",
    descriptionAr: "للأعمال النامية الجاهزة للتوسع",
    savings: "Lower commission (3% vs 5%)",
    savingsAr: "عمولة أقل (3% بدل 5%)",
    badge: "MOST POPULAR",
    badgeAr: "الأكثر طلباً",
    popular: true,
    features: [
      {
        text: "Launch & sell from day one - no developer needed",
        textAr: "ابدأ البيع من اليوم الأول - بدون مبرمج",
        included: true,
        highlight: true,
      },
      {
        text: "Everything in Free",
        textAr: "كل مزايا المجاني",
        included: true,
      },
      {
        text: "Unlimited Products & Orders",
        textAr: "منتجات وطلبات غير محدودة",
        included: true,
        highlight: true,
      },
      {
        text: "Product Image Gallery",
        textAr: "ألبوم صور للمنتجات",
        included: true,
        highlight: true,
      },
      {
        text: "Product Video Upload",
        textAr: "إضافة فيديو للمنتج",
        included: true,
        highlight: true,
      },
      {
        text: "Media Storage: 50 GB",
        textAr: "مساحة تخزين: 50 جيجا",
        included: true,
        highlight: true,
      },
      {
        text: "Driver Management System",
        textAr: "نظام إدارة السائقين",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Real-time Driver Tracking",
        textAr: "تتبع السائقين في الوقت الفعلي",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "All payments in your name",
        textAr: "كل المدفوعات باسمك مباشرة",
        included: true,
        highlight: true,
      },
      {
        text: "Payment Processing (All Gateways)",
        textAr: "معالجة الدفع (جميع البوابات)",
        included: true,
      },
      {
        text: "Cash on Delivery (COD)",
        textAr: "الدفع عند الاستلام",
        included: true,
        highlight: true,
      },
      {
        text: "Discount & Coupon System",
        textAr: "نظام الخصومات والكوبونات",
        included: true,
        highlight: true,
      },
      {
        text: "AI Product Descriptions (Unlimited)",
        textAr: "وصف منتجات بالذكاء الاصطناعي (غير محدود)",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Ship locally & internationally - one contract",
        textAr: "شحن محلي ودولي من عقد واحد",
        included: true,
        highlight: true,
      },
      {
        text: "Stable hosting during peak seasons",
        textAr: "استضافة مستقرة في المواسم والذروة",
        included: true,
        highlight: true,
      },
      {
        text: "SEO Optimized Store",
        textAr: "متجر محسّن لمحركات البحث",
        included: true,
        highlight: true,
      },
      {
        text: "SEO Settings Per Product",
        textAr: "تحسين SEO لكل منتج",
        included: true,
        highlight: true,
      },
      {
        text: "SEO Settings Per Category",
        textAr: "تحسين SEO لكل تصنيف",
        included: true,
        highlight: true,
      },
      {
        text: "Built-in Blog System",
        textAr: "نظام مدونة مدمج",
        included: true,
        highlight: true,
      },
      {
        text: "SEO Settings Per Blog Post",
        textAr: "تحسين SEO لكل مقال",
        included: true,
        highlight: true,
      },
      {
        text: "Auto-share blog posts to Twitter",
        textAr: "مشاركة تلقائية للمقالات على تويتر",
        included: true,
        highlight: true,
      },
      {
        text: "Shipping Integrations (SMSA, Aramex)",
        textAr: "تكامل الشحن (SMSA، أرامكس)",
        included: true,
      },
      {
        text: "Amazon Integration (Global Marketplace)",
        textAr: "تكامل أمازون (سوق عالمي)",
        included: true,
        highlight: true,
      },
      {
        text: "Trendyol Integration (Fashion & Lifestyle)",
        textAr: "تكامل ترينديول (أزياء ومنتجات)",
        included: true,
        highlight: true,
      },
      {
        text: "Jahez Integration (Food Delivery)",
        textAr: "تكامل جاهز (توصيل طعام)",
        included: true,
        highlight: true,
      },
      {
        text: "Custom Domain",
        textAr: "نطاق مخصص",
        included: true,
      },
      {
        text: "Email Marketing Automation",
        textAr: "أتمتة التسويق عبر البريد",
        included: true,
        highlight: true,
      },
      {
        text: "Loyalty & Rewards Program (Advanced)",
        textAr: "برنامج الولاء والمكافآت (متقدم)",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Multi-Currency & Multi-Language",
        textAr: "عملات ولغات متعددة",
        included: true,
        highlight: true,
      },
      {
        text: "Progressive Web App (PWA)",
        textAr: "تطبيق ويب تقدمي (PWA)",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Instagram Shopping Integration",
        textAr: "تكامل التسوق عبر إنستقرام",
        included: true,
        highlight: true,
      },
      {
        text: "Tabby & Tamara BNPL",
        textAr: "تابي وتمارا - اشتر الآن وادفع لاحقاً",
        included: true,
        highlight: true,
      },
      {
        text: "Advanced Analytics",
        textAr: "تحليلات متقدمة",
        included: true,
      },
      {
        text: "Inventory Management & Stock Control",
        textAr: "إدارة المخزون ومراقبة المخزون",
        included: true,
        highlight: true,
      },
      {
        text: "Low Stock SMS Alerts",
        textAr: "تنبيه SMS عند نفاذ المخزون",
        included: true,
        highlight: true,
      },
      {
        text: "ZATCA E-Invoice Compliance (Fatoora)",
        textAr: "إرسال فاتورة ضريبية إلكترونية",
        included: true,
        highlight: true,
      },
      {
        text: "Mini Accounting System",
        textAr: "نظام محاسبة مبسط",
        included: true,
        highlight: true,
      },
      {
        text: "Customer Reviews & Ratings",
        textAr: "تقييمات ومراجعات العملاء",
        included: true,
        highlight: true,
      },
      {
        text: "SEO-Optimized Reviews (Rich Snippets)",
        textAr: "تحسين SEO للتقييمات (نجوم جوجل)",
        included: true,
        highlight: true,
      },
      {
        text: "DreamToApp Store Exposure (Free Traffic)",
        textAr: "عرض في متجر DreamToApp (زيارات مجانية)",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Featured in DreamToApp Store",
        textAr: "عرض مميز في متجر DreamToApp",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Priority Email Support",
        textAr: "دعم بريدي ذو أولوية",
        included: true,
      },
      {
        text: "Remove DreamToApp Branding",
        textAr: "إزالة علامة DreamToApp",
        included: true,
      },
    ],
    cta: "Get Master",
    ctaAr: "احصل على ماستر",
    ctaLink: "https://myshop.dreamto.app/auth/register?plan=master",
  },
  {
    id: "premium",
    name: "Premium",
    nameAr: "بريميوم",
    price: 199,
    priceAr: "١٩٩",
    period: "SAR/month + 2% commission",
    periodAr: "ر.س/شهرياً + عمولة 2%",
    tagline: "Professional Power, Unbeatable Price",
    taglineAr: "قوة احترافية، سعر لا يُقهر",
    description: "For established businesses and enterprises",
    descriptionAr: "للشركات الراسخة والمؤسسات",
    savings: "Lowest commission (2%) + best value",
    savingsAr: "أقل عمولة (2%) + أفضل قيمة",
    features: [
      {
        text: "Launch & sell from day one - no developer needed",
        textAr: "ابدأ البيع من اليوم الأول - بدون مبرمج",
        included: true,
        highlight: true,
      },
      {
        text: "Everything in Master",
        textAr: "كل مزايا ماستر",
        included: true,
      },
      {
        text: "Product Image Gallery",
        textAr: "ألبوم صور للمنتجات",
        included: true,
        highlight: true,
      },
      {
        text: "Product Video Upload",
        textAr: "إضافة فيديو للمنتج",
        included: true,
        highlight: true,
      },
      {
        text: "Media Storage: Unlimited",
        textAr: "مساحة تخزين: غير محدودة",
        included: true,
        highlight: true,
      },
      {
        text: "Ship locally & internationally - one contract",
        textAr: "شحن محلي ودولي من عقد واحد",
        included: true,
        highlight: true,
      },
      {
        text: "Stable hosting during peak seasons",
        textAr: "استضافة مستقرة في المواسم والذروة",
        included: true,
        highlight: true,
      },
      {
        text: "SEO Optimized Store",
        textAr: "متجر محسّن لمحركات البحث",
        included: true,
        highlight: true,
      },
      {
        text: "SEO Settings Per Product",
        textAr: "تحسين SEO لكل منتج",
        included: true,
        highlight: true,
      },
      {
        text: "SEO Settings Per Category",
        textAr: "تحسين SEO لكل تصنيف",
        included: true,
        highlight: true,
      },
      {
        text: "Built-in Blog System",
        textAr: "نظام مدونة مدمج",
        included: true,
        highlight: true,
      },
      {
        text: "SEO Settings Per Blog Post",
        textAr: "تحسين SEO لكل مقال",
        included: true,
        highlight: true,
      },
      {
        text: "Auto-share blog posts to Twitter",
        textAr: "مشاركة تلقائية للمقالات على تويتر",
        included: true,
        highlight: true,
      },
      {
        text: "Shift Management System",
        textAr: "نظام إدارة المناوبات",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Real-time Driver Tracking",
        textAr: "تتبع السائقين في الوقت الفعلي",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Unlimited Team Members",
        textAr: "أعضاء فريق غير محدودين",
        included: true,
        highlight: true,
      },
      {
        text: "Advanced Store Health Reports",
        textAr: "تقارير صحة المتجر المتقدمة",
        included: true,
        highlight: true,
      },
      {
        text: "All payments in your name",
        textAr: "كل المدفوعات باسمك مباشرة",
        included: true,
        highlight: true,
      },
      {
        text: "Amazon Integration (Global Marketplace)",
        textAr: "تكامل أمازون (سوق عالمي)",
        included: true,
        highlight: true,
      },
      {
        text: "Trendyol Integration (Fashion & Lifestyle)",
        textAr: "تكامل ترينديول (أزياء ومنتجات)",
        included: true,
        highlight: true,
      },
      {
        text: "Jahez Integration (Food Delivery)",
        textAr: "تكامل جاهز (توصيل طعام)",
        included: true,
        highlight: true,
      },
      {
        text: "API Access & Webhooks",
        textAr: "الوصول إلى API والخطافات",
        included: true,
      },
      {
        text: "Custom CSS/JS",
        textAr: "CSS/JS مخصص",
        included: true,
      },
      {
        text: "Discount & Coupon System",
        textAr: "نظام الخصومات والكوبونات",
        included: true,
        highlight: true,
      },
      {
        text: "Product Bundles & Packages",
        textAr: "عروض حزم المنتجات",
        included: true,
        highlight: true,
      },
      {
        text: "AI Product Descriptions (Unlimited)",
        textAr: "وصف منتجات بالذكاء الاصطناعي (غير محدود)",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "AI Chatbot Support (24/7)",
        textAr: "دعم بوت ذكي على مدار الساعة",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Cash on Delivery (COD)",
        textAr: "الدفع عند الاستلام",
        included: true,
        highlight: true,
      },
      {
        text: "Email Marketing Automation",
        textAr: "أتمتة التسويق عبر البريد",
        included: true,
        highlight: true,
      },
      {
        text: "Loyalty & Rewards Program (Basic)",
        textAr: "برنامج الولاء والمكافآت (أساسي)",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Multi-Currency Price Display (Hover tooltip)",
        textAr: "عرض الأسعار بعملات متعددة (عند التمرير)",
        included: true,
        highlight: true,
      },
      {
        text: "Progressive Web App (PWA)",
        textAr: "تطبيق ويب تقدمي (PWA)",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "SMS Marketing",
        textAr: "التسويق عبر الرسائل النصية",
        included: true,
      },
      {
        text: "Inventory Management & Stock Control",
        textAr: "إدارة المخزون ومراقبة المخزون",
        included: true,
        highlight: true,
      },
      {
        text: "Low Stock SMS Alerts",
        textAr: "تنبيه SMS عند نفاذ المخزون",
        included: true,
        highlight: true,
      },
      {
        text: "ZATCA E-Invoice Compliance (Fatoora)",
        textAr: "إرسال فاتورة ضريبية إلكترونية",
        included: true,
        highlight: true,
      },
      {
        text: "Mini Accounting System",
        textAr: "نظام محاسبة مبسط",
        included: true,
        highlight: true,
      },
      {
        text: "Instagram Shopping Integration",
        textAr: "تكامل التسوق عبر إنستقرام",
        included: true,
        highlight: true,
      },
      {
        text: "Tabby & Tamara BNPL",
        textAr: "تابي وتمارا - اشتر الآن وادفع لاحقاً",
        included: true,
        highlight: true,
      },
      {
        text: "DreamToApp Store Exposure (Free Traffic)",
        textAr: "عرض في متجر DreamToApp (زيارات مجانية)",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Customer Reviews & Ratings",
        textAr: "تقييمات ومراجعات العملاء",
        included: true,
        highlight: true,
      },
      {
        text: "SEO-Optimized Reviews (Rich Snippets)",
        textAr: "تحسين SEO للتقييمات (نجوم جوجل)",
        included: true,
        highlight: true,
      },
      {
        text: "DreamToApp Store Exposure (Free Traffic)",
        textAr: "عرض في متجر DreamToApp (زيارات مجانية)",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Featured in DreamToApp Store",
        textAr: "عرض مميز في متجر DreamToApp",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Priority Placement in DreamToApp Store",
        textAr: "أولوية الظهور في متجر DreamToApp",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Dedicated Marketing Support",
        textAr: "دعم تسويقي مخصص",
        included: true,
        unique: true,
        highlight: true,
      },
      {
        text: "Priority Phone & Chat Support",
        textAr: "دعم هاتفي ودردشة ذو أولوية",
        included: true,
      },
      {
        text: "Dedicated Account Manager",
        textAr: "مدير حساب خاص لك",
        included: true,
        highlight: true,
      },
    ],
    cta: "Get Premium",
    ctaAr: "احصل على بريميوم",
    ctaLink: "https://myshop.dreamto.app/auth/register?plan=premium",
  },
];

export const comparisonFeatures = [
  {
    feature: "Products",
    featureAr: "المنتجات",
    dreamtoapp: { free: "20", master: "Unlimited", premium: "Unlimited" },
    salla: { basic: "Unlimited", plus: "Unlimited", pro: "Unlimited" },
    zid: { lite: "Unlimited", pro: "Unlimited" },
  },
  {
    feature: "Monthly Price",
    featureAr: "السعر الشهري",
    dreamtoapp: { free: "Free", master: "79 SAR", premium: "199 SAR" },
    salla: { basic: "Free", plus: "99 SAR", pro: "299 SAR" },
    zid: { lite: "83 SAR", pro: "Contact" },
  },
  {
    feature: "Driver Management",
    featureAr: "إدارة السائقين",
    dreamtoapp: { free: false, master: true, premium: true },
    salla: { basic: false, plus: false, pro: false },
    zid: { lite: false, pro: false },
    unique: true,
  },
  {
    feature: "Store Health Monitoring",
    featureAr: "مراقبة صحة المتجر",
    dreamtoapp: { free: true, master: true, premium: true },
    salla: { basic: false, plus: false, pro: false },
    zid: { lite: false, pro: false },
    unique: true,
  },
  {
    feature: "Shift Management",
    featureAr: "إدارة المناوبات",
    dreamtoapp: { free: false, master: false, premium: true },
    salla: { basic: false, plus: false, pro: false },
    zid: { lite: false, pro: false },
    unique: true,
  },
  {
    feature: "Payment Processing",
    featureAr: "معالجة الدفع",
    dreamtoapp: { free: false, master: true, premium: true },
    salla: { basic: false, plus: true, pro: true },
    zid: { lite: true, pro: true },
  },
  {
    feature: "Team Members",
    featureAr: "أعضاء الفريق",
    dreamtoapp: { free: "1", master: "3", premium: "10" },
    salla: { basic: "N/A", plus: "N/A", pro: "Multiple" },
    zid: { lite: "1", pro: "20" },
  },
];


